CREATE TABLE `INT_LOCK` (
  `LOCK_KEY` char(36) NOT NULL DEFAULT '',
  `REGION` varchar(100) NOT NULL DEFAULT '',
  `CLIENT_ID` char(36) DEFAULT NULL,
  `CREATED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`LOCK_KEY`,`REGION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;